<?php

	/*
	 * Fichier : CategoryRepository.php
	 * Auteur: SMITH Emmanuel
	 * Création: 04/03/2016
	 * Modification: 22/03/2016
	 *
	 * Repository pour l'entitée Category
	 */

	namespace s4smithe\VitrineBundle\Repository;
	use Doctrine\ORM\EntityRepository;

	/**
	 * ClientRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class CategoryRepository extends EntityRepository {

		/**
		 * @return array
		 */
		public function findAllOrderedByName() {
			return $this->getEntityManager()
					->createQuery( 'SELECT c FROM s4smitheVitrineBundle:Category c ORDER BY c.name ASC')
					->getResult();
		}

	}
