<?php

	namespace s4smithe\VitrineBundle\Repository;
	use Doctrine\ORM\EntityRepository;

	/**
	 * ClientRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class CategoryRepository extends EntityRepository {

		public function findAllOrderedByName() {
			return $this->getEntityManager()
					->createQuery( 'SELECT c FROM s4smitheVitrineBundle:Category c ORDER BY c.name ASC')
					->getResult();
		}

	}
