<?php

	namespace s4smithe\VitrineBundle\Repository;

	use Doctrine\ORM\EntityRepository;

	/**
	 * CommandeWorkflowRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class CommandeWorkflowRepository extends EntityRepository {
		
	}
	