<?php

	/*
	 * Fichier : LigneCommandeRepository.php
	 * Auteur: SMITH Emmanuel
	 * Création: 20/02/2016
	 * Modification: 22/03/2016
	 *
	 * Repository pour l'entitée LigneCommande
	 */

	namespace s4smithe\VitrineBundle\Repository;

	use Doctrine\ORM\EntityRepository;

	/**
	 * LigneCommandeRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class LigneCommandeRepository extends EntityRepository {
		
	}
