<?php

	/*
	 * Fichier : MarqueRepository.php
	 * Auteur: SMITH Emmanuel
	 * Création: 04/03/2016
	 * Modification: 22/03/2016
	 *
	 * Repository pour l'entitée Marque
	 */

	namespace s4smithe\VitrineBundle\Repository;

	use Doctrine\ORM\EntityRepository;

	/**
	 * MarqueRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class MarqueRepository extends EntityRepository {
		/**
		 * @return array
		 */
		public function findAllOrderedByName() {
			return $this->getEntityManager()
				->createQuery( 'SELECT p FROM s4smitheVitrineBundle:Marque p ORDER BY p.name' )
				->getResult();
			
		}

		/**
		 * @return array
		 * @throws \Doctrine\DBAL\DBALException
		 */
		public function findAllPopular() {
			$stmt = $this->getEntityManager()->getConnection()->prepare(
				'SELECT p.marque_id
				FROM (
					SELECT l.product_id AS id, SUM(l.qte) AS cnt
					FROM lignecommande l
					GROUP BY l.product_id
					ORDER BY cnt DESC ) popu
				NATURAL JOIN product p
				LIMIT 5'
			);

			$stmt->execute();
			$marqueIDs = $stmt->fetchAll();
			$marques = [ ];

			foreach ( $marqueIDs as $id ) {
				$marques[] = $this->getEntityManager()
					->getRepository( 's4smitheVitrineBundle:Marque' )
					->findOneById( $id );
			}

			return $marques;

			// SELECT * FROM ( SELECT l.product_id AS id, count(*) AS cnt FROM lignecommande l GROUP BY l.product_id ORDER BY cnt ) pop NATURAL JOIN product ORDER BY name LIMIT 5
		}
	}
