# src/s4XX/VitrineBundle/Resources/config/doctrine/Category.orm.yml
s4smithe\VitrineBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: s4smithe\VitrineBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
           type: string
           length: 100
    oneToMany:                        # Dans l’entité Category on ajoute un champ
        products:                     # products qui permet d’associer à une Category
             targetEntity: Product    # toutes les entités Products dont le champ
             mappedBy: category       # category pointe vers cette entité.
