# src/s4XX/VitrineBundle/Resources/config/doctrine/Category.orm.yml
s4smithe\VitrineBundle\Entity\Commande:
    type: entity
    table: commande
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
               
        etat:
            type: boolean

    manyToOne:						 # Dans l’entité Product on ajoute un champ
        client:						  # category qui pointe vers une entité Category
            targetEntity: Client			# category_id sera, dans la table, le nom de la clé
            inversedBy: commandes			# étrangère qui référence le champ id d’une
            joinColumn:					# Category
                name: client_id
                referencedColumnName: id

    oneToMany:                        # Dans l’entité Category on ajoute un champ
            lignesommandes:                     # products qui permet d’associer à une Category
                 targetEntity: LigneCommande    # toutes les entités Products dont le champ
                 mappedBy: commande       # category pointe vers cette entité.