s4smithe\VitrineBundle\Entity\Marque:
    type: entity
    table: null
    repositoryClass: s4smithe\VitrineBundle\Repository\MarqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            column: Name
            
    oneToMany:                        # Dans l’entité Category on ajoute un champ
        products:                     # products qui permet d’associer à une Category
             targetEntity: Product    # toutes les entités Products dont le champ
             mappedBy: marque       # category pointe vers cette entité.
    lifecycleCallbacks: {  }
