# ------------------------------- #
# ---------- Panier----------- #
# ------------------------------- #



# ---------- Application ----------

# -- Liste contenue
s4smithe_vitrine_contenuPanier:
     path:     /contenu
     defaults: { _controller: s4smitheVitrineBundle:Panier:contenuPanier}

# -- Ajout d'Article
s4smithe_vitrine_addArticlePanier:
     path:     /addArticle/{id}/{qte}
     defaults: { _controller: s4smitheVitrineBundle:Panier:ajouterArticle, qte: 1}
     requirements:
          id: \d+
          qte: \d+

  # -- Definir qté Article
s4smithe_vitrine_changeQuantityPanier:
    path:     /changeQte/{id}/{qte}
    defaults: { _controller: s4smitheVitrineBundle:Panier:changeQutantity, qte: 1}
    requirements:
        id: \d+
        qte: \d+

# -- Retirer un Articles
s4smithe_vitrine_removeOneArticlePanier:
     path:     /removeOneArticle/{articleId}/{qte}
     defaults: { _controller: s4smitheVitrineBundle:Panier:enleverUnArticle, articleId: 0, qte: 1}
     requirements:
          articleId: \d+
          qte: \d+

# -- Retirer l'Article
s4smithe_vitrine_removeArticlesPanier:
     path:     /removeArticles/{articleId}
     defaults: { _controller: s4smitheVitrineBundle:Panier:enleverArticles, articleId: 0}
     requirements:
          articleId: \d+

# -- Vider
s4smithe_vitrine_emptyPanier:
     path:     /empty
     defaults: { _controller: s4smitheVitrineBundle:Panier:emptyPanier}

# -- Validation du Panier => Commande
s4smithe_vitrine_validationPanier:
     path:     /validation
     defaults: { _controller: s4smitheVitrineBundle:Panier:validation}
