#Panier
s4smithe_vitrine_contenuPanier:
     path:     /contenu
     defaults: { _controller: s4smitheVitrineBundle:Panier:contenuPanier}

s4smithe_vitrine_addArticlePanier:
     path:     /addArticle/{articleId}/{qte}
     defaults: { _controller: s4smitheVitrineBundle:Panier:ajouterUnArticle, articleId: 0, qte: 1}
     requirements:
          articleId: \d+
          qte: \d+

s4smithe_vitrine_removeOneArticlePanier:
     path:     /removeOneArticle/{articleId}/{qte}
     defaults: { _controller: s4smitheVitrineBundle:Panier:enleverUnArticle, articleId: 0, qte: 1}
     requirements:
          articleId: \d+
          qte: \d+

s4smithe_vitrine_removeArticlesPanier:
     path:     /removeArticles/{articleId}
     defaults: { _controller: s4smitheVitrineBundle:Panier:enleverArticles, articleId: 0}
     requirements:
          articleId: \d+

s4smithe_vitrine_emptyPanier:
     path:     /empty
     defaults: { _controller: s4smitheVitrineBundle:Panier:emptyPanier}

s4smithe_vitrine_validationPanier:
     path:     /validation
     defaults: { _controller: s4smitheVitrineBundle:Panier:validation}