s4smithe_vitrine_homepage:
     path:     /accueil/{name}
     defaults: { _controller: s4smitheVitrineBundle:Default:index, name: Visiteur}
     requirements:
          name:	\w+
    
s4smithe_vitrine_mentions:
     path:     /mentions
     defaults: { _controller: s4smitheVitrineBundle:Default:mentions}
     
s4smithe_vitrine_catalogue:
     path:     /catalogue
     defaults: { _controller: s4smitheVitrineBundle:Catalogue:index}
     
s4smithe_vitrine_articlesParCategorie:
     path:     /articlesParCategorie/{catId}
     defaults: { _controller: s4smitheVitrineBundle:Categorie:articlesParCategorie, catId: 1 }
     requirements:
          catId:	\d+

s4smithe_vitrine_articlesParMarque:
     path:     /articlesParMarque/{markId}
     defaults: { _controller: s4smitheVitrineBundle:Marque:articlesParMarque, markId: 0 }
     requirements:
          markId:	\d+
          
          
          
s4smithe_vitrine_contenuPanier:
     path:     /panier/contenu
     defaults: { _controller: s4smitheVitrineBundle:Panier:contenuPanier}
     
s4smithe_vitrine_addArticlePanier:
     path:     /panier/addArticle/{articleId}/{qte}
     defaults: { _controller: s4smitheVitrineBundle:Panier:ajouterUnArticle, articleId: 0, qte: 1}
     requirements:
          articleId: \d+
          qte: \d+
          
s4smithe_vitrine_removeOneArticlePanier:
     path:     /panier/removeOneArticle/{articleId}/{qte}
     defaults: { _controller: s4smitheVitrineBundle:Panier:enleverUnArticle, articleId: 0, qte: 1}
     requirements:
          articleId: \d+
          qte: \d+

s4smithe_vitrine_removeArticlesPanier:
     path:     /panier/removeArticles/{articleId}
     defaults: { _controller: s4smitheVitrineBundle:Panier:enleverArticles, articleId: 0}
     requirements:
          articleId: \d+

s4smithe_vitrine_emptyPanier:
     path:     /panier/empty
     defaults: { _controller: s4smitheVitrineBundle:Panier:emptyPanier}
     
     

s4smithe_vitrine_manager:
     path:     /manager
     defaults: { _controller: s4smitheVitrineBundle:Manager:index }
