s4smithe_vitrine_homepage:
     path:     /accueil/{name}
     defaults: { _controller: s4smitheVitrineBundle:Default:index, name: Visiteur}
     requirements:
          name:	\w+
    
s4smithe_vitrine_mentions:
     path:     /mentions
     defaults: { _controller: s4smitheVitrineBundle:Default:mentions}
     
s4smithe_vitrine_catalogue:
     path:     /catalogue
     defaults: { _controller: s4smitheVitrineBundle:Default:catalogue}
     
s4smithe_vitrine_articlesParCategorie:
     path:     /articlesParCategorie/{catId}
     defaults: { _controller: s4smitheVitrineBundle:Default:articlesParCategorie, catId: 1 }
     requirements:
          catId:	\d+

s4smithe_vitrine_manager:
     path:     /manager
     defaults: { _controller: s4smitheVitrineBundle:Manager:index }
