s4smithe_vitrine_homepage:
    path:     /accueil/{name}
    defaults: { _controller: s4smitheVitrineBundle:Default:index, name: Visiteur}
    
s4smithe_vitrine_mentions:
    path:     /mentions
    defaults: { _controller: s4smitheVitrineBundle:Default:mentions}
