# src/s4smithe/VitrineBundle/Resources/config/validation.yml

# ---------- Client ----------
s4smithe\VitrineBundle\Entity\Client:
    properties:
        name:
            - NotBlank:
                message: Le nom ne doit pas être vide.

        password:
            - NotBlank:
                message: Le mot de passe ne doit pas être vide.

            - Type: password

        mail:
            - NotBlank:
                message: Le mot de passe ne doit pas être vide.

            - Email:
                message: L'email "{{ value }}" n'est pas un email valide.
                checkMX: true

        address:
            - NotBlank:
                message: L'adresse ne doit pas être vide.

        tel:
            - NotBlank:
                message: Le téléphone ne doit pas être vide.

            - Regex:
                pattern: '/^\+?\d{10,12}/'
                message: Le numero de téléphone n'est pas valide. Ex: 0123456789 ou +33123456789.

        dateBirthday:
            - Date:
                message: La date de naissance n'est pas valide.

            - Type: \DateTime



# ---------- Product ----------
s4smithe\VitrineBundle\Entity\Product:
    properties:
        name:
            - NotBlank:
                message: Le nom ne doit pas être vide.

        file:
            - Image:
                allowLandscape: false
                allowPortrait: false
                mimeTypesMessage: Le fichier n'est pas supporté
                maxSize: 6000000

        price:
            - NotBlank:
                message: Le prix ne doit pas être vide.

            - Type: scalar

            - Range:
                min: 0.0
                minMessage: Le nombre doit être strictement positif.

        stock:
            - Type: int

            - Range:
                min: 0
                minMessage: Le nombre doit être strictement positif.

        description:
            - NotBlank:
                message: La description ne doit pas être vide.

        category:
            - NotBlank:
                message: Le produit doit avoir une catégoire.

        marque:
            - NotBlank:
                message: Le produit doit avoir une marque.



# ---------- Marque ----------
s4smithe\VitrineBundle\Entity\Marque:
    properties:
        name:
            - NotBlank:
                message: Le nom ne doit pas être vide.

            - Length:
                min: 5
                max: 100
                minMessage: Le nom doit comporter au moins 5 caractères.
                maxMessage: Le nom ne doit pas exceder 100 caractères.



# ---------- Category ----------
s4smithe\VitrineBundle\Entity\Category:
    properties:
        name:
            - NotBlank:
                message: Le nom ne doit pas être vide.

            - Length:
                min: 5
                max: 100
                minMessage: Le nom doit comporter au moins 5 caractères.
                maxMessage: Le nom ne doit pas exceder 100 caractères.
